-- Seed Data for Devine Water Management System
-- Updated for UUID primary keys

-- Note: UUIDs will be auto-generated by the database
-- Password hash for all demo accounts: admin123/user123/customer123
-- Hash: $2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS

-- ============================================
-- INSERT ADMIN USERS
-- ============================================

INSERT INTO users (name, email, password, role, phone, status) VALUES
('Super Admin', 'admin@devinewater.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'SUPER_ADMIN', '+923001234567', 'active'),
('Admin User', 'admin2@devinewater.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'ADMIN', '+923001234568', 'active'),
('Staff User', 'user@devinewater.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'USER', '+923001234569', 'active');

-- ============================================
-- INSERT DEMO CUSTOMERS
-- ============================================

INSERT INTO customers (name, email, password, role, phone, address, cnic, connection_id, connection_type, status) VALUES
('John Doe', 'customer@devinewater.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'CUSTOMER', '+923011234567', '123 Main Street, Karachi', '42101-1234567-1', 'CID-001', 'residential', 'active'),
('Jane Smith', 'jane@example.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'CUSTOMER', '+923011234568', '456 Park Avenue, Lahore', '42101-7654321-2', 'CID-002', 'commercial', 'active'),
('Ahmed Ali', 'ahmed@example.com', '$2a$10$jqCLYz4i7z1XxOCQF8y2MeJLqPvZ8sT1gH/rVHJpKqOk2i9pV7yZS', 'CUSTOMER', '+923011234569', '789 Business Road, Islamabad', '42101-9876543-3', 'CID-003', 'commercial', 'active');

-- ============================================
-- SAMPLE DATA WITH UUID REFERENCES
-- ============================================

-- Note: We'll use subqueries to get UUIDs of inserted records
-- Insert sample consumption data
INSERT INTO consumption (customer_id, reading_date, previous_reading, current_reading, recorded_by)
SELECT 
    c.id,
    '2024-12-01'::DATE,
    0,
    1245.50,
    u.id
FROM customers c
CROSS JOIN users u
WHERE c.email = 'customer@devinewater.com'
  AND u.email = 'admin@devinewater.com'
LIMIT 1;

INSERT INTO consumption (customer_id, reading_date, previous_reading, current_reading, recorded_by)
SELECT 
    c.id,
    '2024-12-01'::DATE,
    0,
    2890.75,
    u.id
FROM customers c
CROSS JOIN users u
WHERE c.email = 'jane@example.com'
  AND u.email = 'admin@devinewater.com'
LIMIT 1;

INSERT INTO consumption (customer_id, reading_date, previous_reading, current_reading, recorded_by)
SELECT 
    c.id,
    '2024-12-01'::DATE,
    0,
    4567.25,
    u.id
FROM customers c
CROSS JOIN users u
WHERE c.email = 'ahmed@example.com'
  AND u.email = 'admin@devinewater.com'
LIMIT 1;

-- Insert sample billing data
INSERT INTO billing (customer_id, billing_period, consumption_liters, tariff_rate, base_amount, tax_amount, total_amount, due_date, status)
SELECT 
    id,
    '2024-12',
    1245.50,
    2.00,
    2491.00,
    249.10,
    2740.10,
    '2025-01-15'::DATE,
    'pending'
FROM customers
WHERE email = 'customer@devinewater.com';

INSERT INTO billing (customer_id, billing_period, consumption_liters, tariff_rate, base_amount, tax_amount, total_amount, due_date, status)
SELECT 
    id,
    '2024-12',
    2890.75,
    2.50,
    7226.88,
    722.69,
    7949.57,
    '2025-01-15'::DATE,
    'pending'
FROM customers
WHERE email = 'jane@example.com';

INSERT INTO billing (customer_id, billing_period, consumption_liters, tariff_rate, base_amount, tax_amount, total_amount, due_date, status)
SELECT 
    id,
    '2024-12',
    4567.25,
    3.00,
    13701.75,
    1370.18,
    15071.93,
    '2025-01-15'::DATE,
    'paid'
FROM customers
WHERE email = 'ahmed@example.com';

-- Insert payment for the paid bill
INSERT INTO payments (billing_id, customer_id, amount, payment_method, transaction_id, status)
SELECT 
    b.id,
    c.id,
    15071.93,
    'bank_transfer',
    'TXN-2024-12-20-001',
    'completed'
FROM billing b
JOIN customers c ON b.customer_id = c.id
WHERE c.email = 'ahmed@example.com'
  AND b.billing_period = '2024-12';

-- Insert sample complaints
INSERT INTO complaints (customer_id, title, description, category, priority, status, assigned_to)
SELECT 
    c.id,
    'Low Water Pressure',
    'Water pressure has been very low for the past week',
    'supply',
    'high',
    'open',
    u.id
FROM customers c
CROSS JOIN users u
WHERE c.email = 'customer@devinewater.com'
  AND u.email = 'user@devinewater.com'
LIMIT 1;

INSERT INTO complaints (customer_id, title, description, category, priority, status, assigned_to)
SELECT 
    c.id,
    'Incorrect Bill Amount',
    'The bill amount seems higher than expected',
    'billing',
    'medium',
    'in_progress',
    u.id
FROM customers c
CROSS JOIN users u
WHERE c.email = 'jane@example.com'
  AND u.email = 'user@devinewater.com'
LIMIT 1;

-- ============================================
-- INSERT SYSTEM SETTINGS
-- ============================================

INSERT INTO settings (setting_key, setting_value, description) VALUES
('default_tariff_rate', '2.00', 'Default tariff rate per liter for residential'),
('commercial_tariff_rate', '2.50', 'Tariff rate per liter for commercial'),
('industrial_tariff_rate', '3.00', 'Tariff rate per liter for industrial'),
('tax_percentage', '10', 'Tax percentage applied to bills'),
('payment_due_days', '15', 'Number of days before payment is due'),
('system_email', 'noreply@devinewater.com', 'System email for notifications'),
('company_name', 'Devine Water', 'Company name'),
('support_phone', '+92-300-1234567', 'Customer support phone number');
